### ISSUE TITLE
Add new Namespaces

### ISSUE THREAD

**Issue by sergioib** [IAAA-Lab/pid-ms#13]
Add new Namespace to prove if it is working correctly

- [x] Hidrografía (Aguas Físicas), http://www.ign.es/wfs-inspire/hidrografia
- [x] Hidrografía 1:100.000, http://www.ign.es/wfs-inspire/hidrografia-btn100
- [x] Ocupación de suelo, http://www.ign.es/wfs-inspire/ocupacion-suelo

**Comment by sergioib** [comment]
Hidrografía (Aguas Físicas), http://www.ign.es/wfs-inspire/hidrografia, has been tested add only one feature, it works correctly.
Hidrografía 1:100.000, http://www.ign.es/wfs-inspire/hidrografia-btn100, has been added with more than one features separate by coma, it works correctly
Ocupación de suelo, http://www.ign.es/wfs-inspire/ocupacion-suelo, is slow, the management of timeouts has been correctly tested.

**Comment by fjlopez** [comment]
Can you add them to [namespaces.csv]?(../blob/master/src/main/resources/config/liquibase/namespaces.csv)
