### ISSUE TITLE
Checkbox doesn't send false value in creation form

### ISSUE THREAD

**Issue by sergioib** [IAAA-Lab/pid-ms#15]
When a new entity is added, the checkbox in the form doesn't send false value by default. It is necessary select an deselect the checkbox.

**Comment by fjlopez** [comment]
Can you add a screenshot of the form with an arrow pointing to the checkbox related to the issue?

**Comment by sergioib** [comment]
It happens in all checkbox when you want to create a new Entity. This problem has been only resolved in the Namespace creation.

**Comment by fjlopez** [comment]
This bug is originated in state.js 
```javascript
.state('namespace.new', {
            onEnter: ['$stateParams', '$state', '$uibModal', function($stateParams, $state, $uibModal) {
                $uibModal.open({
                    resolve: {
                        entity: function () {
                            return {
                                publicNamespace: false, 
                                resolverProxyMode: null,
                                hitsRequest: null,
                                ...
```
The above code provide default values in the new namespace form. I have removed the added `ngInit` and replaced the `null` values by `false` in the commit 2b896ebd6adc284216b8f9fb64325152701ea4db
