### ISSUE TITLE
Attributes derived from Registration must not be not editable

### ISSUE THREAD

**Issue by sergioib** [IAAA-Lab/pid-ms#30]
When a Namespaces is create, add automatically some attributes, for instance, "Namespace Status", "Process Status", "Item Status", "Last Change Date", "Registration Date".

Also it is necessary limit the attributes which can be modified when a Namespace is edited, for example,  "Registration Date", "Last Change Date"

**Comment by sergioib** [comment]
The attributes limitation when they are been editing is only in the application. They can be modified if the API is used

**Comment by fjlopez** [comment]
This is also a problem of any resource that embeds `Registration` data (`Namespace` and `Persistent Identifier`)
