### ISSUE TITLE
What is the License?

### ISSUE THREAD

**Issue by Delawen** [IAAA-Lab/pid-ms#40]
I can't find the license of this software. Is it free? Is it open? Can other countries reuse it freely?

**Comment by Delawen** [comment]
I guess this means it is not free.

**Comment by fjlopez** [comment]
@Delawen, I'm sorry I took so long to answer you. We are preparing a stable release that will have a EUPL 1.2 license. It will be available in two weeks or less.

**Comment by fjlopez** [comment]
Done
